eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
#          uri: https://git.oschina.net/chrywhy/test
#          searchPaths: spring-cloud/helloworldConfig
          uri: https://github.com/gouhechuan/JavaTest/
          searchPaths: SpringCloudEx/configDirEx
          username: gouhechuan
          password: g136843716
  application:
    name: config-server